USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS GITHUB_CICD_ROLE;

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE GITHUB_CICD_ROLE;
GRANT USAGE ON DATABASE DBT_TEST_DEV TO ROLE GITHUB_CICD_ROLE;
GRANT USAGE ON DATABASE DBT_TEST_STAGE TO ROLE GITHUB_CICD_ROLE;
GRANT USAGE ON DATABASE DBT_TEST_PROD TO ROLE GITHUB_CICD_ROLE;
GRANT USAGE ON SCHEMA DBT_TEST_DEV.DEV TO ROLE GITHUB_CICD_ROLE;
GRANT USAGE ON SCHEMA DBT_TEST_STAGE.PROD TO ROLE GITHUB_CICD_ROLE;
GRANT USAGE ON SCHEMA DBT_TEST_PROD.PROD TO ROLE GITHUB_CICD_ROLE;

-- Add any other privileges your CI needs:
GRANT CREATE DATABASE ON ACCOUNT TO ROLE GITHUB_CICD_ROLE; -- Becuase of the clone database operation
GRANT CREATE TABLE ON SCHEMA DBT_TEST_STAGE.PROD TO ROLE GITHUB_CICD_ROLE;
GRANT CREATE TABLE ON SCHEMA DBT_TEST_PROD.PROD TO ROLE GITHUB_CICD_ROLE;
GRANT CREATE DBT PROJECT ON SCHEMA DBT_TEST_DEV.DEV TO ROLE GITHUB_CICD_ROLE;

GRANT USAGE ON DATABASE TB_101 TO ROLE GITHUB_CICD_ROLE;
GRANT USAGE ON SCHEMA TB_101.RAW TO ROLE GITHUB_CICD_ROLE;
GRANT select ON ALL TABLES in schema TB_101.RAW TO ROLE GITHUB_CICD_ROLE;


CREATE USER IF NOT EXISTS GITHUB_OIDC_USER
  TYPE = SERVICE
  DEFAULT_ROLE       = GITHUB_CICD_ROLE
  DEFAULT_WAREHOUSE  = COMPUTE_WH
  DEFAULT_NAMESPACE  = DBT_TEST_DEV.DEV
  WORKLOAD_IDENTITY = (
    TYPE   = OIDC
    ISSUER = 'https://token.actions.githubusercontent.com'
    SUBJECT = 'repo:arturoramoss/dbt-snowflake-test:environment:prod'
  );

GRANT ROLE GITHUB_CICD_ROLE TO USER GITHUB_OIDC_USER;

----- This could be necesary if the tables are created first with another role (or you could drop all the tables from the schemas)
GRANT OWNERSHIP ON TABLE IDENTIFIER('"DBT_TEST_STAGE"."PROD"."COUNTRY"') TO ROLE IDENTIFIER('"GITHUB_CICD_ROLE"');
GRANT OWNERSHIP ON TABLE IDENTIFIER('"DBT_TEST_STAGE"."PROD"."COUNTRY_REPORT"') TO ROLE IDENTIFIER('"GITHUB_CICD_ROLE"');
GRANT OWNERSHIP ON TABLE IDENTIFIER('"DBT_TEST_PROD"."PROD"."COUNTRY"') TO ROLE IDENTIFIER('"GITHUB_CICD_ROLE"');
GRANT OWNERSHIP ON TABLE IDENTIFIER('"DBT_TEST_PROD"."PROD"."COUNTRY_REPORT"') TO ROLE IDENTIFIER('"GITHUB_CICD_ROLE"');