USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS GITHUB_CICD_ROLE;

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE GITHUB_CICD_ROLE;
GRANT USAGE ON DATABASE DBT_TEST_DEV TO ROLE GITHUB_CICD_ROLE;
GRANT USAGE ON DATABASE DBT_TEST_STAGE TO ROLE GITHUB_CICD_ROLE;
GRANT USAGE ON DATABASE DBT_TEST_PROD TO ROLE GITHUB_CICD_ROLE;
GRANT USAGE ON SCHEMA DBT_TEST_DEV.DEV TO ROLE GITHUB_CICD_ROLE;
GRANT USAGE ON SCHEMA DBT_TEST_STAGE.PROD TO ROLE GITHUB_CICD_ROLE;
GRANT USAGE ON SCHEMA DBT_TEST_PROD.PROD TO ROLE GITHUB_CICD_ROLE;

-- Add any other privileges your CI needs:
-- GRANT CREATE TABLE ON SCHEMA DEV_DB.PUBLIC TO ROLE GITHUB_CICD_ROLE;


CREATE USER IF NOT EXISTS GITHUB_OIDC_USER
  TYPE = SERVICE
  DEFAULT_ROLE       = GITHUB_CICD_ROLE
  DEFAULT_WAREHOUSE  = COMPUTE_WH
  DEFAULT_NAMESPACE  = DBT_TEST_DEV.DEV
  WORKLOAD_IDENTITY = (
    TYPE   = OIDC
    ISSUER = 'https://token.actions.githubusercontent.com'
    SUBJECT = 'repo:arturoramoss/dbt-snowflake-test:environment:prod'
  );

GRANT ROLE GITHUB_CICD_ROLE TO USER GITHUB_OIDC_USER;