dbt_snowflake_project:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: GITHUB_CICD_ROLE
      database: DBT_TEST_DEV
      schema: dev 
      warehouse: COMPUTE_WH
    stage:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: GITHUB_CICD_ROLE
      database: DBT_TEST_STAGE
      schema: prod
      warehouse: COMPUTE_WH