dbt_snowflake_project:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: ACCOUNTADMIN
      database: SNOWFLAKE_LEARNING_DB
      schema: dev 
      warehouse: COMPUTE_WH
    prod:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: ACCOUNTADMIN
      database: SNOWFLAKE_LEARNING_DB
      schema: prod
      warehouse: COMPUTE_WH